aayushraj1010/med-genie

CODE_OF_CONDUCT.md

- Added a `CODE_OF_CONDUCT.md` file following the Contributor Covenant v2.0.
**Related Issue**
Closes: #15 
These updates are made to:
- Help first-time contributors understand how to participate in the project.
- Set community standards for respectful and inclusive interaction.
- Align with open-source best practices, especially for GSSoC'25 contributors.
- GSSoC'25 preparation
- General documentation improvement
Let me know if further edits are needed. Happy to collaborate! 🚀

Added  CODE_OF_CONDUCT.md 

---

README.md

🔄 Pull Request: Enhance README with License & Contribution Details
📄 Description:
This PR updates the README.md to include:
A well-formatted 📝 License section with a clickable link to the MIT License.
A new 🤝 Contributing section with contribution steps, guidelines, and contact details.
📌 Motivation:Clarify the licensing terms for users (MIT License).
Encourage and simplify contributions from the open-source community.
🛠️ Changes Made:
Added a "License" section with friendly, readable text.
Included a "Contributing" section with instructions and community guidelines.
Linked contact info for the maintainer: [@vinitjain2005](https://github.com/vinitjain2005)
✅ Checklist:
New branch: update-readme-license
Updated README.md with License and Contribution sections
Commit message: "Add license …

Added license section to README

---

package-lock.json
package.json
src/app/about/page.tsx
src/app/contact/page.tsx
src/app/layout.tsx
src/app/page.tsx
src/components/site-header.tsx

🚀 **PR Description**
- Added **About** and **Contact** pages to the Med Genie site.
- The Contact page includes a fully functional form integrated with **EmailJS** to send emails directly from the frontend.
- All EmailJS credentials are managed securely using environment variables via `.env.local`.
- Provided clear setup instructions to obtain EmailJS **Service ID**, **Template ID**, and **Public Key**.
- Updated the project to utilize NEXT_PUBLIC_ prefixed environment variables for safe access within the Next.js frontend.
⚙️ **Instructions for EmailJS Setup**
🔗 1. **Create EmailJS Account**
Go to [EmailJS website](https://www.emailjs.com/) and create a free account.
📩 2. **Add an Email Service**
Choose an email service (e.g., Gmail, Outlook, or SMTP) and note the Service ID.
🧩 3. …

Added About and Contact pages with EmailJS integration

---

src/app/page.tsx
src/components/chat-input-form.tsx
src/components/chat-message-item.tsx

- Add proper aria-labels to chat input and send button
- Improve screen reader support with descriptive labels
- Add semantic heading structure (h2 for Important Notice)
- Add proper ARIA roles and attributes to chat messages
- Improve keyboard navigation and screen reader experience
- Add loading states with proper accessibility announcements
- Fix heading hierarchy for better document structure

fix: improve accessibility for chat interface and semantic structure

---

README.md
src/app/layout.tsx
src/components/site-header.tsx
src/components/theme-toggle.tsx
src/hooks/use-theme.tsx

This PR introduces a fully functional **Dark Mode Toggle Feature** to the Med-Genie application with smooth transitions, persistent storage, and accessibility support.
---
- 🌗 **Theme Toggle Button** in the top-right corner of the header
- 💾 **Persistent Storage** using `localStorage` to save user preference
- 🖥️ **System Theme Support** that respects the user’s OS-level light/dark mode
- ⚡ **Smooth Transitions** between light and dark themes
- ♿ **Accessibility Support** with ARIA labels for screen readers
---
- Toggle between **Light and Dark** modes with a single click
- Theme preference is **remembered across sessions**
- Default theme follows the **system preference**
- Uses a **custom medical-themed color palette** for the dark mode
- Proper accessibility features for inclusive UX …

Added dark/light mode Toggle

---

src/app/contribute/page.tsx
src/app/layout.tsx
src/components/contribute.tsx
src/components/site-footer.tsx
src/components/site-header.tsx
src/components/topcontributors.tsx

**This PR introduces two significant enhancements to the Med Genie project:**
1.  🔥**Footer Component:**
- Implemented a consistent and responsive site footer matching the overall site theme.
- Footer includes essential links (Contact, About, GitHub) and site branding.
- Text styling updated for better visibility and user experience, including hover effects.
2. 🌟**Contribute Section with Dynamic Top Contributors:**
- Added a Contribute component/page that outlines contribution steps clearly to encourage community involvement.
- Integrated live **GitHub API** calls to fetch, sort, and display the top contributors dynamically from the project’s repository.
- Fetch logic retrieves contributor data such as username, avatar, profile URL, and contribution count, displaying the seven most active …

🚀 Add Footer Component & Dynamic Top Contributors Section with GitHub API Integration 🎉

---

src/app/page.tsx
src/components/chat-input-form.tsx
src/components/site-header.tsx

📝 Description:
A reset button placed next to the Dark/Light mode toggle in the navbar. The Reset button allows users to clear or reset the current page view or inputs (as applicable), enhancing usability.
💻 Changes Made:
Added a Reset button in the navbar layout.
Styled it consistently with the existing UI.
Ensured the button appears neatly beside the Dark/Light mode toggle.

Add Reset Button beside Dark/Light mode toggle in navbar

---

src/app/api/nearby-hospitals/route.ts
src/app/page.tsx

hey @Nitin10cd 
https://drive.google.com/file/d/1rd7_xSyOojaoKffgjwd6W_bjP3IOYJy8/view?usp=sharing
I have implemented 
Feature Request: Nearby Hospital Helpline Integration #12
**Title**: Implemented Nearby Hospital Feature using OGD API
**Description**:
* Extracts state/city from user input in chatbot conversation
* Calls the `/api/nearby-hospitals?state=<state>` endpoint
* Integrates Open Government Data (OGD) API to fetch hospital data
* Parses and displays hospital name, contact number, and address
* Dynamically renders the information in the chatbot UI
**Files Modified**:
* `src/app/api/nearby-hospitals/route.ts` – New API route to connect with OGD API
* `src/app/page.tsx` – Handles user input and displays response
Please review the changes , Thank you.

Implemented Nearby Hospital Feature using OGD API

---

src/app/page.tsx

In light mode,text can't able to seen.so,i have enhanced in code to clearly visible text in light theme.

Added Features

---

src/app/about/page.tsx

I have successfylly enhanced the about page with eye catching design and adding more insights about the project 
-- now it look more informative and clear/clean look of the project

impreved the about page and add important section in it

---

env.example
src/ai/flows/personalized-health-question-answering.ts
src/app/homepage/page.tsx

This pull request (closes #103 )enhances the personalized health question answering flow by introducing conversation history as context for AI responses and updating relevant input schemas, prompts, and UI logic. The changes ensure that previous messages are considered, leading to more personalized and coherent interactions.
**Conversation history integration:**
* Added a `conversationHistory` field to the `PersonalizedHealthQuestionAnsweringInputSchema` and included it in the input passed to the AI flow, enabling the model to access previous messages for context. [[1]](diffhunk://#diff-c40b8041abf65c389bef0e7a6c3b884fc324ecf313726e929915284475ed3c5eR26) [[2]](diffhunk://#diff-c61b57d2843013b8614bf524b893052594bed8f0bc29e9717be0cd35f0e60c22R219-R241)
* Implemented a helper function …

[Feature and Bugfix] Added chatbot contextual awareness and fixed env.example

---

package-lock.json
package.json
src/app/homepage/page.tsx
src/components/chat-input-form.tsx
src/components/chat-message-item.tsx

_This PR introduces an image upload feature to the chat input area, allowing users to send one or multiple images directly from their device._
- _Added a camera icon button next to the voice search button in the chat input bar._
- _Styled the camera button to match the voice button (black background, centered icon, rounded)._
- _Added file input logic with:_
`accept="image/*" `to allow all image formats (JPG, JPEG, PNG, GIF, WebP, etc.).
`multiple` attribute to allow uploading multiple images at once.
- _On file selection, images are previewed in the chat by:_
Creating object URLs from the uploaded files.
Appending them to the chat state as user messages.
- _Adjusted spacing between the camera and voice buttons for better UI alignment._
_Before: (No image upload option)_
_After: (Image …

Added the upload image button in the chat beside voice note button

---

src/app/homepage/page.tsx
src/components/QuickReplyGrid.tsx
src/lib/prompts.ts

This pull request introduces a new feature: **Clickable Quick-Prompts Buttons**. These prompts are fixed in the UI above the chat input area to provide users with constant guidance and a faster way to interact with the chatbot.
This feature is designed to improve the user experience, especially for new users, by showcasing the chatbot's core capabilities and reducing the need to type common queries.
*   **New `QuickReplyGrid.tsx` Component:**
*   Created a new, reusable React component located at `src/components/QuickReplyGrid.tsx`.
*   This component is responsible for rendering the grid of prompt buttons.
*   **Centralized Prompt Management:**
*   Added a new file `src/lib/prompts.ts` to define the titles and corresponding queries for the quick-reply buttons. This makes it easy to …

Feature: Implemented fixed quick-prompts buttons for user guidance

---

package.json
src/ai/flows/specialist-recommendation.ts
src/app/api/specialist-recommendation/route.ts
src/app/specialist-recommendation/page.tsx
src/components/landing_page/NavBar.tsx
src/components/site-header.tsx

- Add specialist recommendation page with user input form
- Implement comprehensive rule-based recommendation API
- Add navigation links in header and navbar
- Include symptom-based specialist matching
- Support for emergency condition detection
- Clean, simple UI design with card-based layout
Brief description of what this PR does and why it's needed.
Fixes #(issue number)
Please delete options that are not relevant.
#112 
Describe the tests that you ran to verify your changes.
Add screenshots to help explain your changes.
**Before:**
**After:**
How does this change improve healthcare accessibility or user experience?
How does this change affect accessibility?
Add any other notes about the pull request here.
List any related issues or pull requests.
---
**Thank you for contributing to …

feat: implement doctor specialist recommendation feature (#112)

---

public/privacypolicy.css
public/privacypolicy.html
src/components/landing_page/Footer.tsx
src/components/landing_page/privacypolicy.css
src/components/landing_page/privacypolicy.html
src/components/site-footer.tsx

Added contents of privacy policy file.

Added Privacy Policy 

---

SECURITY_CONFIGURATION.md
next.config.ts
src/app/layout.tsx
src/lib/jwt.ts
src/lib/rate-limit.ts
src/lib/types.ts
src/middleware.ts

Fix:- #121 
Create a `.env` file in your project root with the following security configuration:
```bash
ALLOWED_ORIGINS=http://localhost:9003,https://med-genie-five.vercel.app
CSP_REPORT_URI=https://med-genie-five.vercel.app/csp-report
HSTS_MAX_AGE=31536000
JWT_SECRET=your-super-secret-jwt-key-change-in-production
JWT_EXPIRES_IN=7d
RATE_LIMIT_LOGIN_MAX=5
RATE_LIMIT_LOGIN_WINDOW=900000
RATE_LIMIT_REGISTER_MAX=3
RATE_LIMIT_REGISTER_WINDOW=3600000
RATE_LIMIT_CHECK_EMAIL_MAX=10
RATE_LIMIT_CHECK_EMAIL_WINDOW=900000
RATE_LIMIT_GENERAL_MAX=100
RATE_LIMIT_GENERAL_WINDOW=900000
```
- **X-Frame-Options**: Prevents clickjacking attacks
- **X-Content-Type-Options**: Prevents MIME type sniffing
- **X-XSS-Protection**: Enables XSS protection
- **Referrer-Policy**: Controls referrer information
- …

Missing security headers and cors configuration

---

SECURITY_CONFIGURATION.md
next.config.ts
src/app/layout.tsx
src/lib/jwt.ts
src/lib/rate-limit.ts
src/lib/types.ts
src/middleware.ts

**Missing Rate Limiting on Authentication Endpoints** - Level 3 Security Vulnerability
The critical security vulnerability has been fully resolved with a comprehensive rate limiting implementation.
- **File**: `src/lib/rate-limit.ts`
- **Purpose**: Main rate limiting logic with IP-based tracking
- **Features**: 
- Progressive blocking (warning → blocking → recovery)
- Automatic cleanup and memory management
- Fail-safe design (graceful degradation)
- **File**: `src/lib/rate-limit-config.ts`
- **Purpose**: Environment-specific rate limiting settings
- **Environments**:
- Development: More permissive for testing
- Production: Strict security limits
- Testing: Very permissive for CI/CD
- **File**: `src/lib/rate-limit-redis.ts`
- **Purpose**: Scalable rate limiting for production
- …

Missing Rate Limiting on Authentication Endpoints attempt 2

---

health-vault.html
public/privacypolicy.html

Reverts aayushraj1010/med-genie#152

Revert "Pre-Loader & AOS Animations "

---

src/app/specialist-recommendation/page.tsx

I changed the Button's text from 'Clear' to 'Reset'. Kindly review the PR.

fix: improved the clear Button label to Reset #130

---

src/app/cookie-policy/page.tsx
src/app/terms-of-use/page.tsx
src/components/site-footer.tsx

This PR adds the missing Cookie Policy and Terms of Use pages to the Med-Genie app and updates the footer links to point to these pages instead of 404s.
Issue #173 
Changes included:
Added src/app/cookie-policy/page.tsx with Cookie Policy content.
Added src/app/terms-of-use/page.tsx with Terms of Use content.
Footer (src/components/site-footer.tsx) already contains links to these pages, ensuring proper navigation.
Before:
Clicking Cookie Policy or Terms of Use in the footer resulted in 404 errors.
After:
Both links now open the correct pages with proper content.
Testing:
Run the app locally: npm run dev.
Scroll to the footer.
Click Cookie Policy → page loads correctly.
Click Terms of Use → page loads correctly.

Add Cookie Policy and Terms of Use pages with updated footer links
